// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQ5s1IsEZYWpHtmks3SMCk5lYefvYAMkQ',
    appId: '1:816583824921:web:77305ddf8cf654e7e2bc88',
    messagingSenderId: '816583824921',
    projectId: 'xrdock-app',
    authDomain: 'xrdock-app.firebaseapp.com',
    storageBucket: 'xrdock-app.firebasestorage.app',
    measurementId: 'G-TSP8QQZ7JL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6WdptGywGzfES6ODZCDJpmVC-tsCSXDo',
    appId: '1:816583824921:android:a88e74dab6600629e2bc88',
    messagingSenderId: '816583824921',
    projectId: 'xrdock-app',
    storageBucket: 'xrdock-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6B6DJUqN-O8uftKDwGrQe9Tw0s6y8wOg',
    appId: '1:816583824921:ios:3a70f526d0a142f4e2bc88',
    messagingSenderId: '816583824921',
    projectId: 'xrdock-app',
    storageBucket: 'xrdock-app.firebasestorage.app',
    iosClientId: '816583824921-3g64jvth3602lgmsjklilc8c3udm1gm3.apps.googleusercontent.com',
    iosBundleId: 'com.kuvira.frontend',
  );

}